### PR TITLE
Fix undefined behavior caused by dereferencing

### LINKED ISSUE #830: unitcase testmerge panic and a UB reported
```
thread 'merge_operator::test::mergetest' panicked at library/core/src/panicking.rs:218:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`

This indicates a bug in the program. This Undefined Behavior check is optional, and cannot be relied on for safety.
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/d5b4c2e4f19b6d7037371cdaecc3cc2c701c68df/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/d5b4c2e4f19b6d7037371cdaecc3cc2c701c68df/library/core/src/panicking.rs:117:22
   2: core::panicking::panic_nounwind_fmt
             at /rustc/d5b4c2e4f19b6d7037371cdaecc3cc2c701c68df/library/core/src/intrinsics/mod.rs:3241:9
   3: core::panicking::panic_nounwind
             at /rustc/d5b4c2e4f19b6d7037371cdaecc3cc2c701c68df/library/core/src/panicking.rs:218:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /root/.rustup/toolchains/nightly-2025-04-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ub_checks.rs:68:21
   5: core::slice::raw::from_raw_parts
             at /root/.rustup/toolchains/nightly-2025-04-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ub_checks.rs:75:17
   6: rocksdb::merge_operator::full_merge_callback
             at ./src/merge_operator.rs:56:9
   7: _ZNK24crocksdb_mergeoperator_t11FullMergeV2ERKN7rocksdb13MergeOperator19MergeOperationInputEPNS1_20MergeOperationOutputE
             at ./librocksdb_sys/crocksdb/c.cc:580:41
   8: _ZN7rocksdb11MergeHelper14TimedFullMergeEPKNS_13MergeOperatorERKNS_5SliceEPS5_RKSt6vectorIS4_SaIS4_EEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6LoggerEPNS_10StatisticsEPNS_11SystemClockEPS4_b
             at ./librocksdb_sys/rocksdb/db/merge_helper.cc:88:42
```

see:   https://blog.rust-lang.org/2024/05/02/Rust-1.78.0/#asserting-unsafe-preconditions

### PR DESCRIPTION
**Pull request by v01dstar**
close #830

### CODE REVIEW

File: src/merge_operator.rs [hunk 1]
```diff
@@ -52,8 +52,16 @@ pub unsafe extern "C" fn full_merge_callback(
     let cb: &mut MergeOperatorCallback = &mut *(raw_cb as *mut MergeOperatorCallback);
     let operands = &mut MergeOperands::new(operands_list, operands_list_len, num_operands);
     let key: &[u8] = slice::from_raw_parts(raw_key as *const u8, key_len);
-    let oldval: &[u8] = slice::from_raw_parts(existing_value as *const u8, existing_value_len);
-    let mut result = (cb.merge_fn)(key, Some(oldval), operands);
+    let oldval = if existing_value.is_null() || existing_value_len == 0 {
+        None
+    } else {
+        assert!(existing_value_len <= isize::MAX as size_t);
```
Comment (LykxSassinator) [inline src/merge_operator.rs:58]: Just curious, why can't the maximum size of `existing_value_len` exceed 2 GiB?

Comment (v01dstar) [reply src/merge_operator.rs:58]: It should not in practice, I am just following Rust's requirements for from_raw_part

Comment (v01dstar) [reply src/merge_operator.rs:58]: https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety
